FROM openjdk:21

#WORKDIR /app

COPY ./bank-transaction-management-0.0.1-SNAPSHOT.jar /bank-transaction-management-1.0.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "bank-transaction-management-1.0.jar"]

